version: "0.2"
phases:
  install:
    runtime-versions:
      python: "3.9"
      nodejs: "16"
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  build:
    commands:
      - echo $BRANCH_NAME
      - npm install -g aws-cdk
      - npx cdk --version
      - cd $CODEBUILD_SRC_DIR && npm install projen
      # - cd $CODEBUILD_SRC_DIR src/client && npm install && npm run build
      - cd $CODEBUILD_SRC_DIR && cdk deploy pipeline-$BRANCH_NAME -c TargetStack=Pipeline -c BranchName=$BRANCH_NAME
